# Generated by Django 5.1.6 on 2025-03-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='adddress',
            new_name='address',
        ),
    ]
